IEP009: IntelMQ Data Format: Describe product and mark vulnerabilities
certtools/ieps pull request #10
Opened 2023-11-02 10:28 UTC by kamil-certat

~Note: This PR depends on #9, which is why the IEP008 is visible in the change view. The IEP008 discussion should be proceeded in the appropriate place.~

2023-11-02 13:53 UTC, sebix commented
> Note: This PR depends on #9

Why?

2023-11-02 14:51 UTC, kamil-certat commented
Not a good one, I've just started them as once, and forgotten it doesn't make sense any more. Fixed.

2024-03-07 09:50 UTC, aaronkaplan requested changes
The first sentence is not true actually.

What is true is what's written here: https://docs.intelmq.org/latest/community/?h=hist#short-history

I'd suggest we either remove the first sentnece or link to the actual idea.

just tracking malware was not the goal back then.

2024-03-07 09:50 UTC, aaronkaplan commented on 009/README.md
> +The original intention behind IntelMQ was to track malicious connections. Today we see
that's actually not true :) 
And I should know since I co-defined these original ideas with Tomas L.
So, I highly would advise against that sentence. I would delete it.

2024-03-07 10:00 UTC, kamil-certat commented on 009/README.md
> +The original intention behind IntelMQ was to track malicious connections. Today we see
Oh, I was sure I found it somewhere :O Thanks for the catch!

2024-03-07 10:03 UTC, aaronkaplan approved these changes

2024-03-07 10:04 UTC, merged